DROP TABLE IF EXISTS ARTICLE;
CREATE TABLE ARTICLE (
      ID INT BIGINT AUTO_INCREMENT PRIMARY KEY,
      TITLE VARCHAR(50) NOT NULL,
      AUTHOR VARCHAR(50) NOT NULL,
      CONTENT VARCHAR(100) NOT NULL,
      PUBLISHING_DATE TIMESTAMP NOT NULL
);